# Not recommended for production - high data volume and risk of exposing sensitive content
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
spring.ai.chat.client.observations.include-error-logging=true
spring.ai.tools.observations.include-content=true
spring.ai.vectorstore.observations.log-query-response=true

management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.step=5s
management.metrics.tags.application=${spring.application.name}

management.otlp.tracing.export.enabled=true
management.tracing.sampling.probability=1.0

spring.docker.compose.enabled=true
spring.docker.compose.profiles.active=otel