spring.ai.mcp.client.initialized=false

spring.ai.mcp.client.authorization.dynamic-client-registration.enabled=true
# For development purposes, explicitly allows HTTP for loopback addresses (MCP Security enforces HTTPS for all URLs involved in the Dynamic Client Registration flow)
spring.ai.mcp.client.authorization.dynamic-client-registration.allow-loopback-addresses=true