# These tag appears in all metrics → Correlation with logs/traces
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0
management.otlp.metrics.export.step=5s
management.otlp.metrics.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.profiles.active=otel