spring.autoconfigure.exclude=

spring.docker.compose.enabled=true
spring.docker.compose.profiles.active=mcp-security

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:5556/realms/spring
spring.security.oauth2.resourceserver.jwt.principal-claim-name=email